package com.omega.framework.index;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.omega.framework.index.bean.GUID;
import com.omega.framework.index.bean.IndexCommand;
import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.support.TransactionSynchronizationAdapter;
import org.springframework.transaction.support.TransactionSynchronizationManager;

import java.util.Map;
import java.util.concurrent.TimeUnit;

/**
 * Created by jackychenb on 11/12/2016.
 */

public class IndexService {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private IndexWorkerRegistry indexWorkerRegistry;

    @Autowired
    private IndexWorkerInvoker indexWorkerInvoker;

    @Autowired
    private RedisTemplate redisTemplate;

    @Value("${elasticsearch.index.commandTableName:IndexCommand}")
    private String commandTableName = "IndexCommand";

    @Value("${elasticsearch.refresh.interval:10}")
    private int refreshInterval = 10;

    @Value("${elasticsearch.refresh.duration:500}")
    private long refreshDuration = 500L; // 预估的最长的refresh调用耗时，单位毫秒

    public String exec(final IndexCommand cmd) {
        checkCommand(cmd);

        String dataMapString = null;
        Map<String, String> dataMap = cmd.getDataMap();
        if (dataMap != null) {
            ObjectMapper mapper = new ObjectMapper();
            try {
                dataMapString = mapper.writeValueAsString(dataMap);
            } catch (JsonProcessingException e) {
                throw new RuntimeException(e);
            }
        }

        jdbcTemplate.update("insert into " + commandTableName +
                "(id, type, indexName, op, dataMap) values" +
                "(?, ?, ?, ?, ?)", new Object[] {
                cmd.getId(), cmd.getType(), cmd.getIndexName(), cmd.getOp(), dataMapString
        });

        if (TransactionSynchronizationManager.isActualTransactionActive()) {
            TransactionSynchronizationManager.registerSynchronization(
                    new TransactionSynchronizationAdapter() {
                        public void afterCommit() {
                            invokeCommand(cmd);
                        }
                    });
        } else {
            invokeCommand(cmd);
        }

        return cmd.getId();
    }

    private void invokeCommand(IndexCommand cmd) {
        IndexWorkerRegistry.InvocationTarget invocationTarget = indexWorkerRegistry.getInvocationTarget(cmd.getType());
        indexWorkerInvoker.invoke(cmd, invocationTarget);

        long lifecycle = refreshInterval * 1000 + refreshDuration;
        redisTemplate.opsForValue().set(cmd.getId(), System.currentTimeMillis(), lifecycle, TimeUnit.MILLISECONDS);
    }

    protected void checkCommand(IndexCommand cmd) {
        if (StringUtils.isNotBlank(cmd.getId())) {
            throw new IllegalArgumentException("The command id is to be generated by system");
        }

        String zoneCode = jdbcTemplate.queryForObject("/*!mycat:tag=current_data_node*/ select getTaskZoneCode() from dual", String.class);
        cmd.setId(GUID.get() + zoneCode);

        String type = cmd.getType();
        if (type == null || !type.matches("[a-zA-Z_]+\\w*")) {
            throw new IllegalArgumentException("Illegal command type: " + type);
        }

        String indexName = cmd.getIndexName();
        if (indexName == null || !indexName.matches("[\\w\\-]+")) {
            throw new IllegalArgumentException("Illegal index name: " + indexName);
        }

        int op = cmd.getOp();
        if (IndexCommand.OP_ADD != op && IndexCommand.OP_DELETE != op) {
            throw new IllegalArgumentException("Illegal index operation: " + op);
        }
    }

}
