server:
  port: 8086

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ongo360
    password: ongo360
    virtual-host: ongo360_vhost

mycat:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/sk_dev?useOldAliasMetadataBehavior=true
    username: root
    password: rootpass
    tomcat:
      testOnBorrow: true
  servers: localhost:3306

zookeeper:
  servers: 127.0.0.1:2181

elasticsearch:
  clusterName: omega
  endPoints: localhost:9300
  index:
    scheduler:
      loadInterval: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            timeoutInMilliseconds: 5000

default:
  ribbon:
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 2
    OkToRetryOnAllOperations: true // All operations should be idempotent

endpoints:
  shutdown:
    sensitive: false
    enabled: true

logging:
  path: /var/log
  level:
    root: WARN
    com:
      ongo360:
        demo: DEBUG
